apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-VERSION
  labels:
    app: simpleapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
        version: VERSION
      annotations:
        forceRedeployUniqId: "VERSION"
    spec:
      containers:
      - name: simpleapi
        image: 251159765025.dkr.ecr.us-east-2.amazonaws.com/simpleapi:VERSION
        ports:
        - containerPort: 5000
          name: flask